package org.syncon.tool.JIRA;

import java.util.LinkedList;
import org.apache.log4j.Logger;

public class JIRAimportLogReader {

	// Read the log genearted by JIRA after uploading the
	// failed test cases.

	static Logger log = Logger.getLogger(JIRAimportLogReader.class.getName());

	public static LinkedList<String> logReader(String logData) {
		log.info("Start reading log generated by the JIRA");
		LinkedList<String> elements = new LinkedList<>();
		int startPoint = 0;
		String toBeFind = "Issue created successfully with Key [";
		String nextFind = "summary='";
		while (true) {
			if (startPoint >= logData.length()) {
				break;
			} else {
				int index = logData.indexOf(toBeFind, startPoint);
				if (index != -1) {
					int jiraBugIDIndex = index+toBeFind.length();
					int summaryIndex = logData.indexOf(nextFind, jiraBugIDIndex)+nextFind.length();
					elements.add(logData.substring(summaryIndex, logData.indexOf("'", summaryIndex)));
					elements.add(logData.substring(jiraBugIDIndex, logData.indexOf("]", jiraBugIDIndex)));
					startPoint=index+toBeFind.length();
				} else {
					break;
				}
			}
		}
		log.info("Successfully read the log generated by JIRA");
		return elements;
	}
}
